### PR TITLE
WIP Background color, scatter plot, grid

### PR DESCRIPTION
**Pull request by RomanBapst**
- adds a grid to the plot
- changes background color to white (we could make this selectable)
- adds a checkbox which allows plotting the markers (needs some improvements)
- move the plot calls into update_graph() method (needs some review)
- add some functions like offset, scale, integrator and differentiator
- fixed bug, some logs would not load due to multi_id topics

### CODE REVIEW

**Comment by Marxlp** [comment]
Have you tested you code? You might need to first fork this repo and clone your own fork repo to your computer and then make some improvements, test it and finally make a PR.
Your suggestion is good except that grid can be added by context menu of the graph. Besides Combobox may be better for choosing markers.

**Comment by RomanBapst** [comment]
@Marxlp Hi, yes I've tested my code. The changes I do are mostly related to making this app usable for daily PX4 log analysis. I've been using FlightPlot until now but I like a python based alternative.
I think I've reached a point where I should abstract some functionality into classes, otherwise I think it's going to get a bit messy. The current changes are not necessarily great form an architecture point of view, but rather a quick way to integrate the functionality I need every day. I'm happy to talk about a better integration, especially because I'd like to add many more features.
analysis

**Review by Marxlp — APPROVED** [review]

**Review by Marxlp — APPROVED** [review]

**Review by Marxlp — APPROVED** [review]

**Review by Marxlp — CHANGES_REQUESTED** [review]
Scatter plot is useful. But it isn't suitable to put checkbox on the toolbar, where iconed buttons are placed.

**Review by Marxlp — COMMENTED** [review]
Adding Integrator function and differentiator function are really good idea, but offset and scale are not. Curves on the  graph with different scale and offset settings will confused people if not decorated to make different from those not scaled or offset in same axis coordination, although it may be convenient sometimes and is supported in FlightPlot. 
I think if offset and scale were added, either some notification on curves or some characters on legend should be added too.

**Comment by Marxlp** [comment]
@RomanBapst  I made a new branch **master-dev** to push and review new changes. Your commits were merged here.

**Pull request closed without merging**
