### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by bkueng**
Nice project!

I have 2 minor fixes.

I also noticed that the FFT view does not work with ROI: it always shows the FFT over the full view. Do you plan to change that?

### CODE REVIEW

**Comment by Marxlp** [comment]
Sorry, I don't understand. Does FFT mean Fast Fourier Transform? I didn't add FFT view. Could you describe error with more details.

**Comment by bkueng** [comment]
Yes if you enable ROI via `show/hide ROI graph`, and then FFT via `Plot Options -> Transformations -> Power Spectrum (FFT)`, the FFT is always shown over the whole dataset, instead of only the selected region in the ROI window. Maybe it's an issue in PyQtGraph?

**Comment by Marxlp** [comment]
Yes, it is due to how the pyqtgraph implement the ROI. But may be not a issue. I will change the code to support FFT in Detail_graph view( Just adjust the data range according to ROI ) in several days. If you want, you can add this function and make a PR.

**Comment by bkueng** [comment]
> I will change the code to support FFT in Detail_graph view( Just adjust the data range according to ROI ) in several days. If you want, you can add this function and make a PR.

Ok, thanks. I don't have the bandwidth to look into that at the moment. The FFT view is a valuable feature.

**Pull request merged**
